language: nix
nix: 2.2.2
git:
  depth: 3
  quiet: true
  submodules: false
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - nix-collect-garbage --delete-older-than 30d
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - /nix/store/
jobs:
  include:
    - stage: test
      script: scripts/test.sh
      if: type != cron
    - stage: deploy
      script: scripts/deploy.sh
      if: branch = master AND type = cron
    - stage: channel
      script: scripts/channel.sh
      if: branch = master
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: build
        on:
          branch: master
    - stage: cachix
      script: scripts/cachix.sh
      if: branch = master AND type = cron
