language: nix
nix: 2.2.2
git:
  depth: 3
  quiet: true
  submodules: false
jobs:
  include:
    - stage: test
      script: ./test.sh
      if: type != cron
    - stage: deploy
      script: ./deploy.sh
      if: branch = master AND type = cron
