language: nix
nix: 2.2.2
git:
  depth: 3
  quiet: true
  submodules: false
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jobs:
  include:
    - stage: test
      script: ./test.sh
      if: type != cron
    - stage: deploy
      script: ./deploy.sh
      if: branch = master AND type = cron
    - stage: channels
      script: ./channels.sh
      if: branch = master AND type = cron
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: "$GH_TOKEN"
        local_dir: build
        on:
          branch: master
