name: "Deploy"
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: update android sources
        run: ./scripts/update.sh
      - name: test
        run: ./scripts/test.sh
      - name: push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          ./scripts/deploy.sh
      - name: build nixexprs
        run: ./scripts/channel.sh
      - name: deploy nix channel
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
          SINGLE_COMMIT: true
          GIT_CONFIG_NAME: "github-actions"
          GIT_CONFIG_EMAIL: "github-actions@github.com"
